name: crypto_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  core_module:
    path: libraries/core_module

  dependencies_module:
    path: libraries/dependencies_module

  design_system_module:
    path: libraries/design_system_module


  cupertino_icons: ^1.0.2
  iconly: ^1.0.1
  fl_chart: ^0.55.2
  firebase_core: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Biotif
      fonts:
        - asset: assets/fonts/Biotif-Regular.ttf
    - family: Neuzeit
      fonts:
        - asset: assets/fonts/Neuzeit-Grotesk-Bold.ttf
