name: Crypto App CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    name: Flutter Build

    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "3.3.8"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - run: flutter pub get

      - run: flutter analyze

      - run: flutter test

      - run: flutter test --coverage
      - run: flutter test --machine > test-results.json

      # # Check tests coverage percentual
      - uses: VeryGoodOpenSource/very_good_coverage@v1
        with:
          path: './coverage/lcov.info'
          min_coverage: 70
          exclude: '**/*_observer.dart **/change.dart'

      # Add a .json file with tests status
      - uses: dorny/test-reporter@v1
        with:
          name: Tests Results
          path: test-results.json
          reporter: flutter-json
